# Generated by Django 3.2.8 on 2021-10-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50, unique=True)),
                ('text', models.CharField(max_length=1000, unique=True)),
                ('created_at', models.DateTimeField()),
                ('language', models.CharField(max_length=10)),
                ('mentions', models.CharField(max_length=1000)),
                ('hashtags', models.CharField(max_length=1000)),
                ('media', models.TextField()),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('author_id', models.CharField(max_length=50)),
                ('author_username', models.CharField(max_length=30)),
                ('author_bio', models.CharField(max_length=1000)),
                ('author_name', models.CharField(max_length=200)),
                ('author_followers_count', models.IntegerField()),
                ('author_following_count', models.IntegerField()),
                ('author_tweet_count', models.IntegerField()),
                ('reply_to', models.CharField(default=None, max_length=50)),
                ('retweet_to', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
