# Generated by Django 3.2.8 on 2021-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0002_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='reply_to',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweet_to',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
