# Generated by Django 3.2.8 on 2021-10-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0005_alter_hashtag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='endpoint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='twitter_client.endpoint'),
            preserve_default=False,
        ),
    ]
