# Generated by Django 3.2.8 on 2021-10-22 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0006_auto_20211022_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=2)]),
        ),
    ]
