# Generated by Django 3.2.8 on 2021-10-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0010_auto_20211022_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tweet_count', models.IntegerField()),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter_client.hashtag')),
            ],
        ),
    ]
