# Generated by Django 3.2.8 on 2021-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0011_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='quoted_tweet',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
