# Generated by Django 3.2.8 on 2021-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_client', '0012_tweet_quoted_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='last_tweet',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
