name: deploy-app

on:
  # Trigger the workflow on push,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  build-docker-image:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        working-directory: /root/radiology-tweets
      - run: docker-compose up --build -d


# # Installing the runner
# # Create a folder
# mkdir actions-runner && cd actions-runner
# # Download the latest runner package
# curl -O -L https://github.com/actions/runner/releases/download/v2.283.3/actions-runner-linux-x64-2.283.3.tar.gz
# # Extract the installer
# tar xzf ./actions-runner-linux-x64-2.283.3.tar.gz
# RUNNER_ALLOW_RUNASROOT="1" ./config.sh --url https://github.com/TechniCollins/radiology-tweets --token AI5MT46WUSDQXSMVUOLOJJDBOWQOA
# RUNNER_ALLOW_RUNASROOT="1" ./run.sh

# SOME MORE HELP
# https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

# must not run as sudo
# https://serverfault.com/questions/1052695/must-not-run-with-sudo-while-trying-to-create-a-runner-using-github-actions

